### ISSUE TITLE
bundler 2.1.4 issue

### ISSUE THREAD

**Issue by stevewi** [rubygems/bundler#7601]
I did a

`gem update`

The bundler gem got updated from 2.1.4 from 2.1.2 (which was installed with ruby 2.7.0).  I did a 

`bundle update --all`

on my project after *removing* the **Gemfile.lock**.  Everything proceeded normally.  I started getting warnings that look like this when I run the executable in that project:

```
Warning: the running version of Bundler (2.1.2) is older than the version that created the lockfile (2.1.4). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.1.4`.
```

After doing the above again, I noticed the following in the list of gems installed into the bundle:

```
...
Using opener 0.1.0
Using binman 5.1.0
Using bundler 2.1.2   **<< ?!?**
Using color 1.8
Using parslet 1.8.2
...
```

I uninstalled *bundler-2.1.4* and re-build the project bundle and everything is back to normal.

I've done this a million times...  What did I miss this time?

**Comment by hsbt** [comment]
Can you provide the detail of reproducible instructions with only the command-line?

**Comment by stevewi** [comment]
Here you go...  This happened to be on macOS Catalina (10.15.2) but I get the exact same results in the same way on Debian 10 (64-bit AMD & 32-bit ARM7l).

[bundler-2.1.4.txt](https://github.com/rubygems/bundler/files/4111517/bundler-2.1.4.txt)

**Comment by 127** [comment]
+1

**Comment by 127** [comment]
There's  detailed description of the problem but it's not a bundler problem actually
https://qiita.com/scivola/items/8176304c03a92aebdfe2

**Comment by stevewi** [comment]
You write:
> just run your app trough bundler
> bundle exec bin/rails s

Uh...no...  Why should I have to do that when I've **NEVER EVER** had to do that before.  Besides, part of it runs as part of the email delivery pipeline so not entirely possible.  Better to stick with bundler-2.1.2...

You write: 
> There's detailed description of the problem but it's not a bundler problem actually
> https://qiita.com/scivola/items/8176304c03a92aebdfe2

I don't read Japanese at all...  Can some kind soul post the executive summary?

**Comment by 127** [comment]
> I don't read Japanese at all...

So, do I  ) But nowadays we have a magic Google Translate tool

**Comment by 127** [comment]
I've degraded by the way server from 2.7.0 to 2.6.5  — got gired of devops tuning overhead for 2.7.0
By the way latest bundler 2.1.4 works fine with pevious ruby 2.6.5

**Comment by StuartPBW** [comment]
Same problem here installing ruby 2.7.0. I thought `gem install bundler` would install 2.1.4, but seems it defaults to 2.1.2.

Any updates here?

**Comment by hsbt** [comment]
@StuartPBW It's expected behavior. Not the same problem.

**Comment by StuartPBW** [comment]
@hsbt Right on. Thanks for the clarification.

**Comment by lukeredpath** [comment]
Also having the same problem. What is causing this? Even if I use the binstubs I get this error.

**Comment by mattbrictson** [comment]
For me I would see this warning in Spring-enabled Rails apps on Ruby 2.7.0.

```
$ bin/rails console
Warning: the running version of Bundler (2.1.2) is older than the version that created the lockfile (2.1.4). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.1.4`.
```

My workaround is to modify `bin/spring` as follows:

```diff
diff --git bin/spring bin/spring
index d89ee49..8bf446f 100755
--- bin/spring
+++ bin/spring
@@ -4,6 +4,7 @@
 # It gets overwritten when you run the `spring binstub` command.
 
 unless defined?(Spring)
+  gem 'bundler', '2.1.4' # Match BUNDLED WITH in Gemfile.lock
   require 'rubygems'
   require 'bundler'

```

`bin/rails` now activates the correct version of Bundler and doesn't print a warning.

**Comment by khorio** [comment]
thanks @mattbrictson - works for me!

**Comment by lastobelus** [comment]
also experiencing this problem, in a brand new empty gem project. Also, `gem list bundler` shows the default version as being 2.1.0.pre2 even though it seems to actually be 2.1.2

```
$ gem list bundler

*** LOCAL GEMS ***

bundler (2.1.4, default: 2.1.0.pre.2)
bundler-unload (1.0.2)
guard-bundler (3.0.0)
rubygems-bundler (1.4.5)

$  bundle info bundler
* bundler (2.1.4)
	Summary: The best way to manage your application's dependencies
	Homepage: https://bundler.io
	Path: /Users/lasto/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4

$ which bundle
/Users/lasto/.rvm/gems/ruby-2.7.0/bin/bundle

$ which aruba
/Users/lasto/.rvm/gems/ruby-2.7.0/bin/aruba

$ aruba
Warning: the running version of Bundler (2.1.2) is older than the version that created the lockfile (2.1.4). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.1.4`.
Traceback (most recent call last):
	6: from /Users/lasto/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:10:in `<main>'
	5: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `run'
	4: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `each'
	3: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:50:in `block in run'
	2: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
	1: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- rubygems-bundler/noexec (LoadError)
	17: from /Users/lasto/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:10:in `<main>'
	16: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `run'
	15: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `each'
	14: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:50:in `block in run'
	13: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
	12: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
	11: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
	10: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
	 9: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:131:in `<top (required)>'
	 8: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:124:in `check'
	 7: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:94:in `setup'
	 6: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/bundler.rb:149:in `setup'
	 5: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/bundler/runtime.rb:22:in `setup'
	 4: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
	 3: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/bundler/shared_helpers.rb:297:in `set_bundle_variables'
	 2: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/bundler/rubygems_integration.rb:223:in `bin_path'
	 1: from /Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems.rb:252:in `bin_path'
/Users/lasto/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (2.1.4) required by your /Users/lasto/clients/metafeat/tooledup/skellie/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`
```

**Comment by DeltaFlush** [comment]
Making bundler a default gem in rubygems was a mistake.

**Comment by pucinsk** [comment]
For me installing th newest version (3.1.2) of RubyGems solved this issue. :+1: 
`gem update --system`

**Comment by stevewi** [comment]
> For me installing th newest version (3.1.2) of RubyGems solved this issue. 👍
> `gem update --system`

I tried what you suggest in one of my development projects and there were no changes in the result.

**Comment by pucinsk** [comment]
> > For me installing th newest version (3.1.2) of RubyGems solved this issue. +1
> > `gem update --system`
> 
> I tried what you suggest in one of my development projects and there were no changes in the result.

Mhm. Strange. Okey, then try this flow and let me know results: 
0. Re-install Ruby 2.7.0 (I'm using rvm so `rvm reinstall 2.7.0`)
1. Make sure you have only one version of  bundler which is 2.1.2 - `gem info bundler` 
2. Update ruby gems to the most recent version`gem update --system`
2.1. If you are using rvm then I recommend you to install bundler for in your gemset with `gem install bundler:2.1.2` separaterely
3. Re-install your gems with `rm Gemfile.lock && bundle`

**Comment by stevewi** [comment]
> > 
> > I tried what you suggest in one of my development projects and there were no changes in the result.
> 
> Mhm. Strange. Okey, then try this flow and let me know results:
> 
> 1. Re-install Ruby 2.7.0 (I'm using rvm so `rvm reinstall 2.7.0`)

I removed ruby 2.7.0 **completely** and installed from source.

> 2. Make sure you have only one version of  bundler which is 2.1.2 - `gem info bundler`

The bundler that was installed from source was 2.1.2.

> 3. Update ruby gems to the most recent version`gem update --system`

I updated `rubygems-update` to 3.1.2.

I updated all the gems that needed it. `bundler` was updated to 2.1.4.

>    2.1. If you are using rvm then I recommend you to install bundler for in your gemset with `gem install bundler:2.1.2` separately

I don't use `rvm.`

> 4. Re-install your gems with `rm Gemfile.lock && bundle`

I removed `.bundle`, gem cache  & `Gemfile.lock` in my development project.  Did `bundle update --all`.

The snippet from `Gemfile.lock` is:

```
BUNDLED WITH
   2.1.4
```

When I run the binary, I get:

```
Warning: the running version of Bundler (2.1.2) is older than the version that created the lockfile (2.1.4). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.1.4`.
```

I removed `bundler:2.1.4`

I removed `.bundle`, the gem cache  & `Gemfile.lock` in my development project.  Did `bundle update --all`.

The snippet from `Gemfile.lock` is:

```
BUNDLED WITH
   2.1.2
```

The binary runs correctly...no warning message.

**Comment by pucinsk** [comment]
> > > I tried what you suggest in one of my development projects and there were no changes in the result.
> > 
> > 
> > Mhm. Strange. Okey, then try this flow and let me know results:
> > 
> > 1. Re-install Ruby 2.7.0 (I'm using rvm so `rvm reinstall 2.7.0`)
> 
> I removed ruby 2.7.0 **completely** and installed from source.
> 
> > 1. Make sure you have only one version of  bundler which is 2.1.2 - `gem info bundler`
> 
> The bundler that was installed from source was 2.1.2.
> 
> > 1. Update ruby gems to the most recent version`gem update --system`
> 
> I updated `rubygems-update` to 3.1.2.
> 
> I updated all the gems that needed it. `bundler` was updated to 2.1.4.
> 
> > 2.1. If you are using rvm then I recommend you to install bundler for in your gemset with `gem install bundler:2.1.2` separately
> 
> I don't use `rvm.`
> 
> > 1. Re-install your gems with `rm Gemfile.lock && bundle`
> 
> I removed `.bundle`, gem cache & `Gemfile.lock` in my development project. Did `bundle update --all`.
> 
> The snippet from `Gemfile.lock` is:
> 
> ```
> BUNDLED WITH
>    2.1.4
> ```
> 
> When I run the binary, I get:
> 
> ```
> Warning: the running version of Bundler (2.1.2) is older than the version that created the lockfile (2.1.4). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.1.4`.
> ```
> 
> I removed `bundler:2.1.4`
> 
> I removed `.bundle`, the gem cache & `Gemfile.lock` in my development project. Did `bundle update --all`.
> 
> The snippet from `Gemfile.lock` is:
> 
> ```
> BUNDLED WITH
>    2.1.2
> ```
> 
> The binary runs correctly...no warning message.

Can you show Gemfile? Maybe you hsve added `gem 'bundler'` line to Gemfile?

**Comment by stevewi** [comment]
```
source "https://rubygems.org"
gem "thor"
gem "sqlite3"
gem "dmarc"
gem "mail"
gem "ox"
gem "rubyzip"
gem "ruport"
gem "rubylib", :git => 'ssh://stevewi@niteflyte.net:/home/stevewi/etc/archives/git/rubylib.git'
gem "rubydoc", :git => 'ssh://stevewi@niteflyte.net:/home/stevewi/etc/archives/git/rubydoc.git'
```

**Comment by pucinsk** [comment]
Mhm. Sorry. 
I've tried to reproduce it in clean Docker container with ruby installed from source but it wasn't success.

**Comment by stevewi** [comment]
My scenario is not in a Docker container.
