### ISSUE TITLE
bundler crashes with net-http-persistent 3.x

### ISSUE THREAD

**Issue by pravi** [rubygems/bundler#7651]
Full log and failure here https://ci.debian.net/data/autopkgtest/unstable/amd64/b/bundler/4243952/log.gz

We discussed this with @deivid-rodriguez earlier this month at debian ruby team sprint and he suggested updating bundler to 2.x but it is still failing.

**Comment by pravi** [comment]
I wonder if https://github.com/rubygems/bundler/commit/92bdbeddfc6bcd11b9d7e9c6ebc2568875c7a4ce#diff-14a2622eae7471c92a750dce0bbc6538 is relevant here

**Comment by deivid-rodriguez** [comment]
Hi @pravi, guessing from the backtrace I think the issue here is different.

In ruby 2.7, the URI library has been gemified, so in order to support this new gem, bundler vendors:

* A namespaced version of URI.
* A namespaced version of net-http-persistent 3.x that itself uses the namespaced version of URI.

Like you can see [here](https://salsa.debian.org/ruby-team/bundler/tree/master/lib/bundler/vendor).

If you were using these "vendored" versions, I think it should work, but in the backtrace I see that you're using the debian package of `net-http-persistent`, and the default ruby version of `URI`. I think that's the issue.

I'm aware that you don't like vendoring things in debian packages, but this is necessary for bundler to be able to support gems like `URI`.

Our plan for the future is to not vendor the whole version of these gems, but just the minimal parts of them that we absolutely need to use, but for now bundler needs the whole thing so I don't currently have a solution for this other than recommending that you live with vendoring these libraries inside bundler for the time being.

So, sadly, I don't currently have a solution for this :(

**Comment by pravi** [comment]
@deivid-rodriguez from the log under #Environment it is using ruby 2.5 (ruby 2.7 is not yet default)
```

Ruby          2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux-gnu]
Full Path   /usr/bin/ruby2.5
```

Even though during spring, we said we remove vendored copies, apparently we don't remove it actually. See the installed files list https://packages.debian.org/sid/all/ruby-bundler/filelist

**Comment by deivid-rodriguez** [comment]
I see. In that case, I think the problem is that even if you're not removing the vendored version, you're not actually using it, as you can see in the backtrace:

```
ArgumentError: bad argument (expected URI object or URI string)
  /usr/lib/ruby/2.5.0/uri/common.rb:745:in `URI'
  /usr/lib/ruby/vendor_ruby/net/http/persistent.rb:954:in `request'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/fetcher/downloader.rb:59:in `request'
```

My guess is that even if bundler actually requires the vendored version of this library, the library internally has non-relative requires, so it might be end up jumping into the system version unintentionally due to $LOAD_PATH priority? Merging [this PR](https://github.com/drbrain/net-http-persistent/pull/106) would probably fix that, but I've been ignored there for a long time.

Can you double check whether removing the dependency on ruby-net-http-persistent from [here](https://salsa.debian.org/ruby-team/bundler/blob/master/debian/control#L24) fixes the issue?

**Comment by pravi** [comment]
The vendored version already have that patch and patching net-http-persistent does not fix the problem. I can remove ruby-net-http-persistent from Depends and add to Conflicts. ruby-mechanize is another package that requires ruby-net-http-persistent so it will make bundler and ruby-mechanize not installable together.

**Comment by deivid-rodriguez** [comment]
> The vendored version already have that patch

Right, we're manually including that patch, so that's not it.

So, what I don't understand is that in the backtrace, the system URI is being used (`/usr/lib/ruby/2.5.0/uri/common.rb`), and that's incorrect. We want to vendored URI.

I would expect a backtrace like:

```
  /usr/lib/ruby/vendor_ruby/uri/common.rb:745:in `URI'
  /usr/lib/ruby/vendor_ruby/net/http/persistent.rb:954:in `request'
  /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/fetcher/downloader.rb:59:in `request'
```
