### ISSUE TITLE
Gem::RemoteFetcher::FetchError: too many connection resets

### ISSUE THREAD

**Issue by gamcodev** [rubygems/bundler#7658]
This is a new occurrence of an issue similar to #4545, which was closed so I'm opening a new issue. I'm not sure if this is being caused by bundler or concurrent-ruby (I don't think it's the latter) but here's my stack trace:

```gem install concurrent-ruby -v '1.1.5'
Fetching concurrent-ruby-1.1.5.gem
Fetching concurrent-ruby-1.1.5.gem
#<Thread:0x0000557bf0322280@/usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/request_set.rb:168 run> terminated with exceptio
n (report_on_exception is true):
Traceback (most recent call last):
        22: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
        21: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/resolver/specification.rb:101:in `download'
        20: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/source.rb:206:in `download'
        19: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:159:in `download'
        18: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:308:in `cache_update_path'
        17: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:263:in `fetch_path'

        16: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:222:in `fetch_http'
        15: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:341:in `request'
        14: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/request.rb:157:in `fetch'
        13: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/request.rb:202:in `perform_request'
        12: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/net/http.rb:1479:in `request'
        11: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/net/http.rb:1517:in `transport_request'
        10: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/net/http/response.rb:165:in `reading_body'
         9: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/net/http.rb:1518:in `block in transport_request'
         8: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/request.rb:208:in `block in perform_request'
         7: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/net/http/response.rb:204:in `read_body'
         6: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/net/http/response.rb:283:in `read_body_0'
         5: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/net/http/response.rb:278:in `inflater'
         4: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/net/http/response.rb:293:in `block in read_body_0'
         3: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/net/protocol.rb:159:in `read'
         2: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/net/protocol.rb:210:in `rbuf_fill'
         1: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/openssl/buffering.rb:182:in `read_nonblock'
/usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/openssl/buffering.rb:182:in `sysread_nonblock': Connection reset by peer (Errno::ECONNRESET)
        10: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
         9: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/resolver/specification.rb:101:in `download'
         8: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/source.rb:206:in `download'
         7: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:159:in `download'
         6: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:308:in `cache_update_path'
         5: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:263:in `fetch_path'
         4: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:222:in `fetch_http'
         3: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/remote_fetcher.rb:341:in `request'
         2: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/request.rb:157:in `fetch'
         1: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/request.rb:193:in `perform_request'
/usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/request.rb:249:in `rescue in perform_request': too many connection resets (h
ttps://rubygems.org/gems/concurrent-ruby-1.1.5.gem) (Gem::RemoteFetcher::FetchError)
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    too many connection resets (https://rubygems.org/gems/concurrent-ruby-1.1.5.gem)```
```

This has prevented me from working for 2 days now and I'm out of options. I have confirmed that my own certs are correct and up to date by reinstalling and running update-ca-certificates. The .pem is listed in /etc/ssl/certs. 

What am I missing??? Is there a way to manually add a cert to bundler? Rvm is not much help.

FYI I'm running Ubuntu 19.04, Ruby 2.6.3 and Bundler 2.1.4

**Comment by gamcodev** [comment]
I ran ```gem update --system``` and my problem was solved. I lost 2 days for nothing. I hope this helps someone else and is not for nothing!
